Repository nebari-dev/nebari-jupyterhub-theme, pull requests merged in 2023-01, with the labels that each got.

#11 ENH - Add jinja linter
  .pre-commit-config.yaml
  README.md
  nebari_jupyterhub_theme/templates/login.html
  nebari_jupyterhub_theme/templates/page.html
  nebari_jupyterhub_theme/templates/style.css
  pyproject.toml
Labels: area: ci 👷🏽‍♀️, area: dependencies 📦, needs: review 👀, type: enhancement 💅🏼

#12 ENH - Improve styles and `css` structure
  .github/workflows/release.yaml
  README.md
  nebari_jupyterhub_theme/templates/page.html
  nebari_jupyterhub_theme/templates/style.css
  pyproject.toml
  test_jupyterhub_config.py
Labels: area: accessibility ♿️, area: developer experience, needs: review 👀, type: enhancement 💅🏼

#13 Update version, changelog in preparation for release
  .pre-commit-config.yaml
  CHANGELOG.md
  environment.yaml
  pyproject.toml
Labels: type: release 🏷
